### ISSUE TITLE
Enable visual representations of synapses and gap junctions

### ISSUE THREAD

**Issue by slarson** [NeuroML/org.neuroml.visualiser#21]
Rendered on top of the cylinders, we should have a way to put a colored spot on the cylinder tied to the "fractAlong" property in NeuroML.  Particularly interesting would be a way of seeing all the synaptic positions in solid with the neuronal network transparent.

**Comment by pgleeson** [comment]
This has been superceded by work as part of Geppetto to visualise NeuroML2 networks, see for e.g. https://github.com/openworm/org.geppetto.frontend/issues/169
